[project]
name = "provision"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "requests>=2.32.5",
    "rich>=14.1.0",
    "rich-click>=1.8.9",
]
